pipeline:
  test:
    image: debian:testing
    commands:
      - apt-get update
      - apt-get install -y python3-socks imagemagick python3-setuptools python3-cryptography python3-dateutil python3-idna python3-requests python3-django-timezone-field libimage-exiftool-perl python3-flake8 python3-pyqrcode python3-png python3-bandit imagemagick gnupg
      - python3 epicyon.py --tests
      - python3 epicyon.py --testsnetwork
