#!/bin/bash
if [ -d /etc/epicyon ]; then
    cd /etc/epicyon || exit 0
else
    cd /opt/epicyon || exit 0
fi
git remote set-url origin https://code.freedombone.net/bashrc/epicyon.git
git checkout main
