#!/bin/bash
if [ -d /etc/epicyon ]; then
    cd /etc/epicyon || exit 0
else
    cd /opt/epicyon || exit 0
fi
git stash
git remote set-url origin https://gitlab.com/bashrc2/epicyon.git
git checkout main
chown -R epicyon:epicyon *
chmod 644 *.py
chmod 644 src/*.py
