#!/bin/bash
journalctl -u epicyon | grep 'image binary\|favicon is not an image\|image size before\|watermark failed\|image metadata removal\|media saved to\|failed to restore backup image\|failed to rename image\|media could not be saved to\|failed to delete backup image\|post_message_to_outbox unable to rename\|rename image upload' > .image.txt
if [ ! -f .image.txt ]; then
    echo 'No image warnings'
else
    cat .image.txt
fi
