#!/bin/bash
journalctl -u epicyon | grep 'image binary\|favicon is not an image\|image size before\|watermark failed\|image metadata removal\|media saved to\|failed to restore backup image\|failed to rename image\|media could not be saved to\|failed to delete backup image\|post_message_to_outbox unable to rename\|rename image upload\|uploaded image saved to\|uploaded image not saved\|final uploaded image size\|creating s2s post with no attached media\|creating c2s post with no attached media\|creating s2s post with attached media\|creating c2s post with attached media' > .image.txt
if [ ! -f .image.txt ]; then
    echo 'No image warnings'
else
    cat .image.txt
fi
