#!/bin/bash
dir_name="epicyon"
if [ ! -d /etc/${dir_name} ]; then
	if [ -d /opt/epicyon-tor ]; then
		dir_name="epicyon-tor"
	elif [ -d /opt/epicyon-i2p ]; then
		dir_name="epicyon-i2p"
	elif [ -d /opt/epicyon-yggdrasil ]; then
		dir_name="epicyon-yggdrasil"
	fi
fi

journalctl -u ${dir_name} | grep 'MITM:' > .mitm_events.txt
if [ ! -f .mitm_events.txt ]; then
    echo 'No MITM events'
else
    cat .mitm_events.txt
fi
