#!/bin/bash
dir_name="epicyon"
if [ -d /etc/${dir_name} ]; then
    cd /etc/${dir_name} || exit 0
else
	if [ -d /opt/${dir_name} ]; then
		cd /opt/${dir_name} || exit 0
	else if [ -d /opt/epicyon-tor ]; then
		dir_name="epicyon-tor"
		cd /opt/${dir_name} || exit 0
	else if [ -d /opt/epicyon-i2p ]; then
		dir_name="epicyon-i2p"
		cd /opt/${dir_name} || exit 0
	else if [ -d /opt/epicyon-yggdrasil ]; then
		dir_name="epicyon-yggdrasil"
		cd /opt/${dir_name} || exit 0
fi
git stash
git pull
chown -R ${dir_name}:${dir_name} *
chmod 644 *.py
chmod 644 src/*.py
systemctl restart ${dir_name}
